# For more on configuring pre-commit hooks (see https://pre-commit.com/)

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict

- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)
      files: \.py$

- repo: https://github.com/asottile/pyupgrade
  rev: v2.37.3
  hooks:
    - id: pyupgrade
      args:
        - --py3-plus
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
    args:
    - "--line-length=99"
  - id: black
    alias: black-check
    stages: [manual]
    args:
    - "--line-length=99"
    - "--check"
    - "--diff"
- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
  - id: flake8
    alias: flake8-check
    stages: [manual]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.971
  hooks:
  - id: mypy
